trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Dockerfile

variables:
  # 修改为自己的镜像名称和标签
  imageName: myimage
  imageTag: latest

stages:
  - stage: build
    displayName: Build Docker image
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # 构建 Docker 镜像
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'clay' 
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
              tags: |
                $(imageName):$(imageTag)

