trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Dockerfile

variables:
  # 修改为自己的镜像名称和标签
  imageName: busyimage
  imageTag: v1.0

stages:
  - stage: build
    displayName: Build Docker image
    jobs:
      - job: build
        displayName: Build
        pool:
          name: 'myvm'
        steps:
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'clay/$(imageName)' 
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfilebusybox'
              tags: |
                $(imageTag)
          - task: CmdLine@2
            inputs:
              script: |
                echo ‘docker push’
                docker push swr.ap-southeast-3.myhuaweicloud.com/clay/$(imageName):$(imageTag)
          # 构建 Docker 镜像

