trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Dockerfile

variables:
  # 修改为自己的镜像名称和标签
  imageName: myimage
  imageTag: latest

stages:
  - stage: build
    displayName: Build Docker image
    jobs:
      - job: build
        displayName: Build
        pool:
          name: 'myvm'
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo ‘docker push’
                docker push swr.ap-southeast-3.myhuaweicloud.com/clay/busybox:latest
          # 构建 Docker 镜像
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'clay/$(imageName)' 
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
              tags: |
                $(imageTag)
