trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Dockerfile

variables:
  # 修改为自己的镜像名称和标签
  imageName: myimage
  imageTag: latest

stages:
  - stage: build
    displayName: Build Docker image
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # 构建 Docker 镜像
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: v
              repository: 'dockerhub'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
              tags: |
                $(imageTag)
          # 登录到 Docker Hub
          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              containerRegistry: 'dockerhub'
              command: 'login'
          # 推送 Docker 镜像到 Docker Hub
          - task: Docker@2
            displayName: Push Docker image to Docker Hub
            inputs:
              containerRegistry: 'dockerhub'
              repository: dockerhub
              command: 'push'
              tags: |
                $(imageTag)